version: "3"

services:

  backend:
    env_file:
      - ./.env
    build: ./backend
    container_name: backend
    ports:
    - "9000:9000"
    command: bash -c "npx sequelize-cli db:migrate && npm run dev"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}

  postgres:
    env_file:
      - ./.env
    image: postgres:12.3-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  frontend:
    build: ./frontend
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

networks:
  default:
    external:
      name: interview